version: '3.9'

services:
  mysql-admin-db:
    image: mysql
    container_name: container_mysql-admin-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: adminapp-db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/MYSQL_DATABASE
      SPRING_DATASOURCE_USER: user
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - 3306:3306
    # volumes:
     # - C:/Users/reg_mbadji/Documents/mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD


  phpmyadmin-admin-db:
    container_name: container_phpmyadmin-admindb
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8081:8081
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-admin-db
      PMA_USER: user
      PMA_PASSWORD: user
    depends_on:
      - mysql-admin-db
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local